### ISSUE TITLE
Light Arrows Cutscene check doesn't appear reachable

### ISSUE THREAD

**Issue by aaarizpe** [StripesOO7/oot-tracker#11]
The Light Arrows Cutscene check in Temple of Time never shows up as reachable. I think it should be reachable once you have the Spirit and Shadow medallions.

![image](https://github.com/user-attachments/assets/de5af9a1-73ec-4b72-b227-d48270e6b9d6)

**Comment by StripesOO7** [comment]
yeah. i have it currently set to always show as inaccessible because i havent come around to properly implement the functions for it xD
will do that now.......

**Comment by StripesOO7** [comment]
well at least added a check for the 2 medallions. since the other options for the LACS are not present in the AP options
