### ISSUE TITLE
Lon Lon Ranch checks not reachable

### ISSUE THREAD

**Issue by aaarizpe** [StripesOO7/oot-tracker#14]
Both the Talons Chickens and Song from Malon checks always appear unreachable

![image](https://github.com/user-attachments/assets/40afd922-9658-43fd-958b-c9eafaaecf0a)

**Comment by StripesOO7** [comment]
when connected to the AP server they should become reachable when having Zeldas letter but i will likely alter the logic for it to be tracked manually and appear reachable
