### ISSUE TITLE
Biggoron check appears unreachable

### ISSUE THREAD

**Issue by aaarizpe** [StripesOO7/oot-tracker#15]
The Biggoron check on Death Mountain Trail appears unreachable even with the Claim Check (and all other items)

![image](https://github.com/user-attachments/assets/a59d4ca0-b8b4-4655-b60a-4e29cb045350)

**Comment by StripesOO7** [comment]
same reason as for LLR, the claimcheck is also not toggleable standalone (anymore) will also alter that logic
