### ISSUE TITLE
Rainbow bridge requirements not working

### ISSUE THREAD

**Issue by aaarizpe** [StripesOO7/oot-tracker#17]
If the rainbow bridge requirements are set to 1 or more stones, medallions, or dungeon rewards, none of the items in Ganon's Castle ever appear reachable.

**Comment by StripesOO7** [comment]
Could you provide pictures of the settings and inventory for when it was not working?

**Comment by aaarizpe** [comment]
Sure, here's one example. Starting from a fresh load of the pack, give yourself every stone and medallion:
![image](https://github.com/user-attachments/assets/25591ef7-0434-4dd2-9645-404c7f2bb758)

Next, go into settings and enable **Open Door of Time**. You should see a few checks in Ganon's Castle become reachable, because the **Rainbow Bridge Req.** is set to "open". Next, set the **Rainbow Bridge Req.** to "stones". Those checks in Ganon's Castle are still reachable, because the required number of stones is set to 0. Finally, set **Required for Bridge Spiritual Stones** to any non-zero value, and you will see the checks become unreachable. You can see the same problem by setting **Rainbow Bridge Req.** to "medallions" and changing **Required for Bridge Medallions** or setting **Rainbow Bridge Req.** to "dungeons" and changing **Required for Bridge Dungeon Rewards**.
![image](https://github.com/user-attachments/assets/ce6edcbe-4f98-4188-82c1-108e76ac816c)

**Comment by StripesOO7** [comment]
Thanks. 
I think i have a rough idea for why this is. 
Should he easy to fix thou

**Comment by StripesOO7** [comment]
fixed
