### ISSUE TITLE
Logic Issue: Forest temple/SFM checks show as accessible despite missing ability to enter temple/SFM as adult

### ISSUE THREAD

**Issue by reindeerfog** [StripesOO7/oot-tracker#18]
Using the 0.0.2 release and glitchless logic. I'm not extremely familiar with OOT, so perhaps there is some obscure way to enter forest temple/SFM that I'm unable to remember, but both of these areas show as having checks that are accessible, despite the fact that I do not have Saria's song to get past mido, nor do I have the Minuet of Forest to warp to the SFM. I also do not have the "Mido backflip" trick turned on.

![image](https://github.com/user-attachments/assets/8e38e40f-fe4c-4501-8bef-a673abd99e1b)
![image](https://github.com/user-attachments/assets/492736a3-9cb0-45c5-a2d8-982068c94931)
![image](https://github.com/user-attachments/assets/3f9c1eb0-253b-4b85-9917-b40dea4b89d4)

**Comment by StripesOO7** [comment]
That should already be fixed and coming in the next release 

https://github.com/StripesOO7/oot-tracker/commit/4a493aab0de877a0be26470c183e2e1997162131
