### ISSUE TITLE
wrong logic for child pots 

### ISSUE THREAD

**Issue by TheLynk** [StripesOO7/oot-tracker#2]
there is a logic error because the tracker indicates that I can go to the child's potty in the guard's house because spawn adulte and close time door in setting and no have ocarina but song of time yes 
https://imgur.com/a/nAo2gQj

**Comment by StripesOO7** [comment]
Thanks for the report. its fixed now in main. the pots where missing the correct restrictions so adult was "able" to get child pots and the other way around
