### ISSUE TITLE
Child locations incorrectly showing as available as adult

### ISSUE THREAD

**Issue by G4M3RL1F3** [StripesOO7/oot-tracker#21]
There are a few child only locations I found that the tracker was showing I could get, but I can't because I am stuck as adult (started as adult, Door of Time closed). At the time of writing this, I have basically no items (Hylian shield and one bottle). Here's the list:
- `LH Underwater Near Shore Green Rupee`
- `LLR GS Tree`
- `LLR GS Rain Shed`
- All four night market crates
- `LW Underwater Green Rupee 1` through 7 after getting silver scale

Note that obtaining an ocarina makes the tracker think that I can go be a child, thus marking relevant locations as available. I remove the ocarina from the tracker to get the results, so consider that locations that are accessible from Desert Colossus and Death Mountain Crater might also incorrectly mark child locations as available.

I will update if more are found. Last updated December 10th.

**Comment by StripesOO7** [comment]
Thanks for the report.

`LH Underwater Near Shore Green Rupee` is fixed...adult rule was wrong.
`LLR GS Tree` and `LLR GS Rain Shed`. the rules where mixed up and as child also moved down 1 item thus also `LLR Child Crate` having the wrong rule to it. all fixed
`night market` checks also had the child rules applied to them
`LW Underwater Green Rupee 1-7` age check was missing.

so all fixed. but there are for sure more checks out there that have no all rules correctly applied.

the ocarina making stuff for the other age accessible is a known issue to me that i still need to solve.
