### ISSUE TITLE
Wrong logic in lost wood

### ISSUE THREAD

**Issue by TheLynk** [StripesOO7/oot-tracker#3]
I appeared as an adult and seeing that I only have the songs of time and no ocarina and that I have the door of time to close I should not have the green squares because there is Mido who is blocking the road just before the zora river shortcut
https://imgur.com/a/fssFVUq

**Comment by StripesOO7** [comment]
I think i figured that out yesterday. I somehow had a connection between Kokiri Forest and SFM. This will most likely have been the cause for that error too. But i will still look into it with that fix in it.

**Comment by StripesOO7** [comment]
![LW](https://github.com/user-attachments/assets/509458f9-cea7-436e-a94b-514927f6f726)
does this look right now? with the exact same inventory from your picture and presumably the same settings 
- closed door of time
- adult start
- skip child dtrade
- Token-/pot-/cratesanity

**Comment by TheLynk** [comment]
I will try with the last modification that you made and I will tell you that

**Comment by TheLynk** [comment]
I confirm that the correction is good
