### ISSUE TITLE
Wrong Logic Kokiri Forest (GS)

### ISSUE THREAD

**Issue by TheLynk** [StripesOO7/oot-tracker#7]
![image](https://github.com/user-attachments/assets/77d2cbb8-f3b2-4515-9a18-e2dd79436b9a)
GS House of Twins is exclusive in child age
And
![image](https://github.com/user-attachments/assets/afa6b030-684e-4b55-ba2b-446a9c66b000)
GS Know It All House i have all requierement item to get location

**Comment by StripesOO7** [comment]
GS House of twins is exclusive to adult . but was falsely marked for child......fixed 

GS know it all house is child, nighttime only. requiering either ocarina+sunsong or being able to leave the forest, which in you inventory case is most likely blocked by not being able to go and finish deku tree......but that is guess works right now,
would need more info

**Comment by TheLynk** [comment]
![image](https://github.com/user-attachments/assets/e151ee9e-9552-4b79-8dd8-a65ba7b60e4b)
gs outside House of Twins is exclusif in child age and no requir hookshoot

**Comment by TheLynk** [comment]
![image](https://github.com/user-attachments/assets/90d373df-ba2d-403c-8e61-a1c9dddeafa4)
GS Know It All House is exclusif in adult age and requir hookshoot

**Comment by StripesOO7** [comment]
i can only say whats written in the logic. and that says:

```
"KF GS Know It All House": "
    is_child and can_child_attack and at_night and 
    (had_night_start or can_leave_forest or can_play(Suns_Song))",
"KF GS Bean Patch": "
    can_plant_bugs and can_child_attack",
"KF GS House of Twins": "
    is_adult and at_night and (Hookshot or (logic_adult_kokiri_gs and Hover_Boots))",
```

which is the exact opposite of what you are saying

**Comment by TheLynk** [comment]
> i can only say whats written in the logic. and that says:
> 
> ```
> "KF GS Know It All House": "
>     is_child and can_child_attack and at_night and 
>     (had_night_start or can_leave_forest or can_play(Suns_Song))",
> "KF GS Bean Patch": "
>     can_plant_bugs and can_child_attack",
> "KF GS House of Twins": "
>     is_adult and at_night and (Hookshot or (logic_adult_kokiri_gs and Hover_Boots))",
> ```
> 
> which is the exact opposite of what you are saying

if I understood everything normally with what you indicate in the code I agree with the logic

**Comment by StripesOO7** [comment]
Did you notice any issues with 0.0.3?
