### ISSUE TITLE
wrong logic Lon Lon Ranch Open grotto

### ISSUE THREAD

**Issue by TheLynk** [StripesOO7/oot-tracker#8]
Im stuck in adult age
![image](https://github.com/user-attachments/assets/aa6774ff-ca5f-4814-96f4-ef24449f77df)

![image](https://github.com/user-attachments/assets/5f9df44d-c6af-4a8e-a24d-189013380bbe)
https://www.zeldadungeon.net/wiki/Ocarina_of_Time_Secret_Grottos

**Comment by StripesOO7** [comment]
You are right. Same issue as Kokiri Forest. Missing restriction on adult timeline

**Comment by StripesOO7** [comment]
fixd.
almost all the checks also where accessible even when they should have been child only. also fixed in the process
